### PR TITLE
Bucanl PR

### PR DESCRIPTION
**Pull request by cll008**
#31

### CODE REVIEW

**Comment by arnodelorme** [comment]
Is there a way we could hand pick the commits. I think there is an option to allow edit when you submit a pull request.

**Comment by arnodelorme** [comment]
Sounds good. If he does not answer, we can review them together.

Arno

**Comment by Andesha** [comment]
hello! I am available to discuss things, but I believe my colleague and I will need to re-familiarize with the code as it has been quite awhile. I will have them post here and then get back to you later this week.

**Comment by cll008** [comment]
That's great Tyler, thanks so much and keep us posted.

**Comment by arnodelorme** [comment]
Thanks Tyler. Looking forward to hear from you by the end of the week.
This repo is very important to us.

Cheers, Arno

**Comment by SaraStephenson** [comment]
Hello, Tyler has brought this conversation to my attention and we have started to review the code and commits. 

Best, Sara

**Comment by Andesha** [comment]
Here's a list of our current thoughts:

* JSONio
  * The JSON package most likely no longer matters
  * It has been quite some time, but we believe JSONio did not support writing of nested matlab structures to file at the time
  * As long as the JSON package you are using supports it, it should not matter
* pop_exportbids.m
  * We never used the internal EEGLAB study structure, so using your version of the script makes the most sense
  * We only ever used EEG as an array, i.e. EEG[0] is the first in the study EEG[1] is the second, to simulate a study
* eegplugin_bids.m
  * Since this is just menu customization and pathing manipulation you can just use your version of course
*  bids_export.m
   * This is of course the file with the bulk of the changes
   * It is very difficult just from the diff/meld to see what would be needed
   * Is there an ongoing feature from my version you would like to bring over?

Hope this clears up at least some of the conflicts. Perhaps a meeting would be best to discuss the complications surrounding the bids_export.m script.

Lastly we will of course be happy to test your version of the plugin once you deem in ready with the Face13 (James Desjardins') training data set.

**Comment by cll008** [comment]
Thanks Tyler and Sara for the effort and the summary. Arno and I just went through bids_export and will test some things out. We were wondering about the `byJson` gInfo field you added... is this also for internal use for your json handling? It's not something that is in (or that you are suggesting for) the BIDS spec is it?

**Comment by Andesha** [comment]
It is indeed not part of the standard.

Judging by my use of it in the code I believe I used it as a function parameter for notifying the exporter of when to handle special array cases. I have a very strong memory of battling how matlab treated structs/cells/arrays in json :laughing: 

Most likely the json exporter you are using more modern and up to date and will support the operations you desire.

**Comment by cll008** [comment]
Thanks for the clarification!

**Comment by Andesha** [comment]
Sure thing.

However, I'll have @SaraStephenson run it and report back :)

**Pull request closed without merging**
